baseURL = "https://tobiojekanmi.github.io/"
languageCode = "en-us"
title = "Oluwatobi's Logbook"
theme = "github-style"
pygmentsCodeFences = true
pygmentsUseClasses = true

[params]
    author = "Oluwatobi Ojekanmi"
    description = "Every cloud has a silver lining."
    github = "tobiojekanmi"
    twitter = "tobiojekanmi"
    linkedin = "tobiojekanmi"
    instagram = "tobiojekanmi"
    email = "oluwatobi.ojekanmi@gmail.com"
    url = "https://tobiojekanmi.github.io"
    keywords = "blog, google analytics"
    rss = true
    lastmod = true
    userStatusEmoji = "😀"
    favicon = "/images/main/favicon.ico"
    headerIcon = "/images/main/favicon.ico"
    avatar = "/images/main/avatar.png"
    location = "Lagos, Nigeria"
    enableGitalk = false

[params.gitalk]
    clientID = "Your client ID"
    clientSecret = "Your client secret"
    repo = "repo"
    owner = "tobiojekanmi"
    admin = "tobiojekanmi"
    id = "location.pathname"
    labels = "gitalk"
    perPage = 15
    pagerDirection = "last"
    createIssueManually = true
    distractionFreeMode = false

[frontmatter]
    lastmod = ["lastmod", ":fileModTime", ":default"]

[services]
    [services.googleAnalytics]
        ID = "UA-123456-789"
